import { newAlbum } from "../js/album.js";
import { newArtist } from "../js/artist.js";
import { newComment } from "../js/comment.js";
import { newEditorial } from "../js/editorial.js";
import { newGenre } from "../js/genre.js";
import { newInfo } from "../js/info.js";
import { newPlaylist } from "../js/playlist.js";
import { newRadio } from "../js/radio.js";
import { newSearch } from "../js/search.js";
import { newTrack } from "../js/track.js";
import { newLogin } from "../js/login.js";

newAlbum();
newArtist();
newComment();
newEditorial();
newGenre();
newLogin();
newPlaylist();
newRadio();
newSearch();
newTrack();
newInfo();
